@basePath = http://localhost:8000
@apiPath = {{basePath}}/api


### Get all Books
GET {{apiPath}}/books


### Get Existing Book the-accursed god
GET {{apiPath}}/books/the-accursed-god



### Get Invlid Book
GET {{apiPath}}/books/invalid-id

### Add a new book
POST {{apiPath}}/books
content-type: application/json

{
    "id":"kurukshetra",
    "title":"Kurukshtrea",
    "authorId":"ramdhari-singh-dinkar",
    "author":"Ramdhari Singh Dinkar",
    "description":"poetic tale of post Kurukshtrea war",
    "rating":4.4,
    "price":99,
    "cover":"kurkshetra.png"
}







### Get Newly added book
GET {{apiPath}}/books/kurukshetra

### Update Newly added book (PUT)
PUT {{apiPath}}/books/kurukshetra
content-type: application/json

{
    "id":"kurukshetra",
    "title":"Kurukshtrea",
    "author":"Ramdhari Singh Dinkar",
    "description":"poetic tale of post Kurukshtrea war",
    "rating":4.4,
    "price":199   
}

### Partial Update book

PATCH {{apiPath}}/books/kurukshetra
content-type: application/json

{
    "price":9
}


### Check if book is updated

GET {{apiPath}}/books/kurukshetra


### Delete Newly added book
DELETE {{apiPath}}/books/kurukshetra

### Check if book is deleted

GET {{apiPath}}/books/kurukshetra

### Get all books after deleting
GET {{apiPath}}/books




### Add a book with invalid details
POST {{apiPath}}/books
content-type: application/json

{
    
    "title":"Manas", 
    "description":"poetic analysis of Mahabharata",
    "price":"free",
    "cover":"kurkshetra.png"
}

### Verify Manas is not added

GET {{apiPath}}/books/manas 


### Add a book with autogenerated id
POST {{apiPath}}/books
content-type: application/json

{
    
    "title":"Manas",
    "author":"Vivek Dutta Mishra",
    "description":"poetic analysis of Mahabharata",
    "rating":4.4,
    "price":99,
    "cover":"kurkshetra.png"
}


### Verify Manas is Added
GET {{apiPath}}/books/manas 

### Delete manas
DELETE {{apiPath}}/books/manas


### Verify Manas is Removed
GET {{apiPath}}/books/manas 


